version: '2'
services:
    nginx-proxy:
     image: jwilder/nginx-proxy
     container_name: nginx-proxy-dev
     ports:
         - "80:80"
     volumes:
         - /var/run/docker.sock:/tmp/docker.sock:ro
    public:
     image: dmitrovskiy/docker-nginx-php-fpm:1.0.0-alpine
     container_name: app-public-dev
     environment:
         - VIRTUAL_HOST=public.site.org
     volumes:
         - ./modules/public/app:/var/www/html/web
         - ./modules/public/src/default.conf:/etc/nginx/conf.d/default.conf
    paypal:
     image: dmitrovskiy/docker-nginx-php-fpm:1.0.0-alpine
     container_name: app-paypal-dev
     environment:
         - VIRTUAL_HOST=paypal.site.org
     volumes:
         - ./modules/paypal/app:/var/www/html/web
         - ./modules/paypal/src/default.conf:/etc/nginx/conf.d/default.conf
    reports:
     image: dmitrovskiy/docker-nginx-php-fpm:1.0.0-alpine
     container_name: app-reports-dev
     environment:
         - VIRTUAL_HOST=reports.site.org
     volumes:
         - ./modules/reports/app:/var/www/html/web
         - ./modules/reports/src/default.conf:/etc/nginx/conf.d/default.conf
    invoice:
     image: dmitrovskiy/docker-nginx-php-fpm:1.0.0-alpine # orionla2/invoice_microservice:latest
     container_name: app-invoice-dev
     environment:
         - VIRTUAL_HOST=invoice.site.org
     volumes:
         - ./modules/invoice/app:/var/www/html/web
         - ./modules/invoice/src/default.conf:/etc/nginx/conf.d/default.conf
    postgresql:
     image: postgres
     container_name: postgresql-dev
     ports:
         - "5432:5432"
     environment:
         - "POSTGRES_USER=postgres"
         - "POSTGRES_PASSWORD=1q2w3e4r"
         - "POSTGRES_DB=postgres"
     volumes:
         - ./srv/docker/postgresql/data:/var/lib/postgresql/data
         - ./srv/docker/db_backup:/home
    schema_setup:
        build: ./modules/migration/src
        image: postgrestdb_schema_setup
        environment:
         - "POSTGRES_USER=postgres"
         - "POSTGRES_PASSWORD=1q2w3e4r"
         - "POSTGRES_DB=postgres"
         - "PGHOST=target_service"
         - "PGPASSWORD=1q2w3e4r"
         - "SQITCH_BUNDLE_REPO=https://github.com/anddorua/ymigration.git"
        links:
         - postgresql-dev:target_service
        volumes:
         - ./migration/src:/src
        depends_on:
         - postgresql-dev
        command: /src/start.sh
    postgrest:
     build: dockerfiles/main
     container_name: postgrest-dev
     environment:
         - "POSTGREST_VERSION=0.3.2.0"
         - "POSTGREST_DBHOST=postgresql-dev"
         - "POSTGREST_DBPORT=5432"
         - "POSTGREST_DBNAME=postgres"
         - "POSTGREST_ANONYMOUS=guest"
         - "POSTGREST_DBUSER=authenticator"
         - "POSTGREST_SCHEMA=my_yacht"
         - "POSTGREST_DBPASS=password"
         - "POSTGREST_PORT=80"
         - VIRTUAL_HOST=site.org
     links:
         - postgresql-dev:postgresql-dev
     depends_on:
         - postgresql-dev
