-- Deploy clearance
-- requires: appschema

BEGIN;

DROP SCHEMA if exists auth cascade;
DROP SCHEMA if exists my_yacht cascade;
DROP EXTENSION IF EXISTS plpgsql CASCADE;
DROP EXTENSION IF EXISTS pgcrypto CASCADE;
DROP TYPE IF EXISTS jwt_claims CASCADE;
DROP TYPE IF EXISTS token_type_enum CASCADE;
DROP FUNCTION IF EXISTS check_role_exists() CASCADE;
DROP FUNCTION IF EXISTS clearance_for_role() CASCADE;
DROP FUNCTION IF EXISTS current_email() CASCADE;
DROP FUNCTION IF EXISTS encrypt_pass() CASCADE;
DROP FUNCTION IF EXISTS send_validation() CASCADE;
DROP FUNCTION IF EXISTS user_role() CASCADE;
DROP FUNCTION IF EXISTS login() CASCADE;
DROP FUNCTION IF EXISTS request_password_reset() CASCADE;
DROP FUNCTION IF EXISTS reset_password() CASCADE;
DROP FUNCTION IF EXISTS signup() CASCADE;
DROP FUNCTION IF EXISTS update_users() CASCADE;
DROP FUNCTION IF EXISTS request_password_reset() CASCADE;
DROP FUNCTION IF EXISTS reset_password() CASCADE;
DROP FUNCTION IF EXISTS public.signup(email text, pass text) CASCADE;
DROP FUNCTION IF EXISTS update_users() CASCADE;

DROP TABLE IF EXISTS tokens CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS additional CASCADE;
DROP SEQUENCE IF EXISTS additional_id_seq CASCADE;
DROP TABLE IF EXISTS booking CASCADE;
DROP SEQUENCE IF EXISTS booking_id_seq CASCADE;
DROP TABLE IF EXISTS devices CASCADE;
DROP SEQUENCE IF EXISTS devices_id_seq CASCADE;
DROP TABLE IF EXISTS download CASCADE;
DROP SEQUENCE IF EXISTS download_id_seq CASCADE;
DROP TABLE IF EXISTS extras CASCADE;
DROP SEQUENCE IF EXISTS extras_id_seq CASCADE;
DROP TABLE IF EXISTS file CASCADE;
DROP SEQUENCE IF EXISTS file_id_seq CASCADE;
DROP TABLE IF EXISTS invoice CASCADE;
DROP SEQUENCE IF EXISTS invoice_id_seq CASCADE;
DROP TABLE IF EXISTS packages CASCADE;
DROP SEQUENCE IF EXISTS packages_id_seq CASCADE;
DROP TABLE IF EXISTS payment CASCADE;
DROP SEQUENCE IF EXISTS payment_id_seq CASCADE;
DROP TABLE IF EXISTS "user" CASCADE;
DROP SEQUENCE IF EXISTS user_id_seq CASCADE;
DROP VIEW IF EXISTS users CASCADE;
DROP TABLE IF EXISTS yacht CASCADE;
DROP SEQUENCE IF EXISTS yacht_id_seq CASCADE;
DROP VIEW IF EXISTS users CASCADE;

DROP OWNED BY manager;
DROP ROLE IF EXISTS manager;
DROP OWNED BY user_role;
DROP ROLE IF EXISTS user_role;
DROP OWNED BY authenticator;
DROP ROLE IF EXISTS authenticator;
DROP OWNED BY guest;
DROP ROLE IF EXISTS guest;

COMMIT;
